[server]
# The address where the server will listen for client and browser connections.
# Set this to "0.0.0.0" to make your app accessible from other devices on your network.
address = "0.0.0.0"

# The port where the server will listen for browser connections.
# This should match the container port in your docker-compose.yaml.
port = 8501 # Or whatever port your Streamlit app is configured to run on inside the container.

# Enables support for Cross-Origin Resource Sharing (CORS) protection.
# Keep this as true for external access.
enableCORS = true

# Optional: If you encounter CORS issues, you might need to add your phone's IP here,
# but usually "0.0.0.0" for 'address' and the port mapping in Docker Compose
# is sufficient for local network access.
# corsAllowedOrigins = ["http://<192.168.1.124:8501"]

[theme]

# The preset Streamlit theme that your custom theme inherits from.
# Using dark theme as base to match Airtel's modern, professional look
base = "dark"

# Primary accent color - Airtel Red
primaryColor = "#E53935"

# Background color of the app - Dark background for professional look
backgroundColor = "#0D1117"



# Color used for almost all text - White for maximum contrast
textColor = "#FFFFFF"

# Color used for all links - Airtel Red variant
linkColor = "#FF4B4B"


# The font family for all text - Clean, modern sans-serif
font = "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif"

# The font family to use for code - Monospace for better readability
codeFont = "JetBrains Mono, Consolas, Monaco, Courier New, monospace"

# Sets the font size for code blocks
codeFontSize = "0.875rem"

# The font family to use for headings - Same as body for consistency
headingFont = "Inter, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif"

